Please, give me an initial code review
Dzuchun/type-matrux pull request #1
Opened 2023-10-08 10:10 UTC by Dzuchun

2023-10-09 05:58 UTC, NYBACHOK commented on derives/src/lib.rs
> +fn data_field(name: Ident) -> proc_macro2::TokenStream {
I think you should use composition and `#[serde("flatten")]` instead of simulating inheritance.

2023-10-09 06:01 UTC, NYBACHOK commented on src/client/impls/reqwest.rs
> +        assert_eq!(response.status(), StatusCode::OK, "Unexpected status code");
Are u sure about needing to paste `assert_eq` here?

2023-10-09 06:01 UTC, NYBACHOK commented on src/client/impls/reqwest.rs
> +        assert_eq!(response.status(), StatusCode::OK, "Unexpected status code");
Maybe I'm missing smth, but it will panic

2023-10-09 06:03 UTC, NYBACHOK commented on src/client/impls/reqwest.rs
> +macro_rules! auth_send_ok {
You really love macroses?

2023-10-09 06:46 UTC, Dzuchun commented on src/client/impls/reqwest.rs
> +        assert_eq!(response.status(), StatusCode::OK, "Unexpected status code");
yeah, It will, I thought I would be a good idea to panic in case of unexpected response

But now, when I thing about it, I should probably add one more variant to error, representing this situation. Thanks for bringing it up.

2023-10-09 06:47 UTC, Dzuchun commented on src/client/impls/reqwest.rs
> +macro_rules! auth_send_ok {
I hate boilerplate.

2023-10-09 06:49 UTC, Dzuchun commented on src/client/impls/reqwest.rs
> +macro_rules! auth_send_ok {
Oh, I guess in this particular case — this macro was intended to perform auth-specific # operations AND regular json parsing. json_ok! is actually used above a lot separately.

2023-10-09 09:10 UTC, shurikv requested changes

2023-10-09 09:10 UTC, shurikv commented on Cargo.toml
> +lazy_static = "1.4.0"
As I know lazy_static and once_cell very similar crates. So maybe would better use one of it and remove one dependency from dev-dependencies?

2023-10-09 11:22 UTC, alexandera5 approved these changes
Looks good to me! Clever and convenient usage of macros.

2023-10-09 11:22 UTC, alexandera5 commented on src/client/impls/reqwest.rs
> +    fn drop(&mut self) {
If you want to keep this behavior, consider describing it in the trait impl docs.
As for me, I would prefer to have a blocking version of the logout request (e.g., using reqwest::blocking) in the drop so that I always know when the drop executes, the logout did work.

I also liked the alternative [solution with a task channel](https://stackoverflow.com/questions/71541765/rust-async-drop/71741467#71741467), because it would explicitly move the actual logout responsibility to some parent entity (client or connection manager), not hide async operation in the destructor.

2023-10-09 11:22 UTC, alexandera5 commented on src/object/mod.rs
> +            Err(_) => Ok(None), // FIXME I guess, that's not the best practice, definitely should redo that
Maybe just return the deserialization error as is?

2023-10-09 21:31 UTC, danik-tro approved these changes

2023-10-11 11:01 UTC, Dzuchun commented on src/object/mod.rs
> +            Err(_) => Ok(None), // FIXME I guess, that's not the best practice, definitely should redo that
As far as I understand it, it would produce an error for this field missing. Which is not what I want (this deserialization function is used for a struct that **might** have a date missing :idk:)

2023-10-11 11:08 UTC, Dzuchun commented on src/client/impls/reqwest.rs
> +    fn drop(&mut self) {
Yeah, I guess I could add `log_out` function to the interface and make it non-async.

The problem is, I cannot consume `self` then (drop can't transfer ownership + the trait would not be object-safe then, but I'd really like it to be such).
I'd like for `log_out` to be consuming, as it's supposed to destroy the session, and thus it's in-code representation (in this case - `Auth` struct).

So I still feel kinda stuck and with no better alternative...

2023-10-11 11:09 UTC, Dzuchun commented on Cargo.toml
> +lazy_static = "1.4.0"
That's a valid point, I guess.

Thanks for bringing it up.

2023-10-15 17:06 UTC, shurikv approved these changes

2023-11-16 09:19 UTC, merged